//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHl7Service")]
public interface IHl7Service
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHl7Service/ProcessHl7Message", ReplyAction="http://tempuri.org/IHl7Service/ProcessHl7MessageResponse")]
    string ProcessHl7Message(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHl7Service/ProcessHl7Message", ReplyAction="http://tempuri.org/IHl7Service/ProcessHl7MessageResponse")]
    System.Threading.Tasks.Task<string> ProcessHl7MessageAsync(string message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHl7ServiceChannel : IHl7Service, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Hl7ServiceClient : System.ServiceModel.ClientBase<IHl7Service>, IHl7Service
{
    
    public Hl7ServiceClient()
    {
    }
    
    public Hl7ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Hl7ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Hl7ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Hl7ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ProcessHl7Message(string message)
    {
        return base.Channel.ProcessHl7Message(message);
    }
    
    public System.Threading.Tasks.Task<string> ProcessHl7MessageAsync(string message)
    {
        return base.Channel.ProcessHl7MessageAsync(message);
    }
}
