# write me a github action that deploy a WCF service to App Service
name: Deploy WCF Service to Azure App Service

on:
  push:
    branches:
      - master
    paths:
      - 'src/WCFService/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'soap-x4hi4xuofqytw'
  AZURE_WEBAPP_PACKAGE_PATH: 'src/WCFService/HL7Service'
  
jobs:
  deploy-wcf-service:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2 
      
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
        run: nuget restore packages.config -SolutionDirectory ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # - name: Run MSBuild
      #   run: msbuild .\HL7Service.sln /p:Configuration=Release
      #   working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
      # - name: Login via Az module
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{secrets.AZURE_CREDENTIALS}}          

      # - name: 'Run Azure webapp deploy action using publish profile credentials'
      #   uses: azure/webapps-deploy@v2
      #   with: 
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'